/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify;

import static com.apideck.unify.operations.Operations.AsyncRequestOperation;

import com.apideck.unify.models.operations.AccountingSalesOrdersAddRequest;
import com.apideck.unify.models.operations.AccountingSalesOrdersAllRequest;
import com.apideck.unify.models.operations.AccountingSalesOrdersDeleteRequest;
import com.apideck.unify.models.operations.AccountingSalesOrdersOneRequest;
import com.apideck.unify.models.operations.AccountingSalesOrdersUpdateRequest;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersAddRequestBuilder;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersAddResponse;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersAllRequestBuilder;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersAllResponse;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersDeleteRequestBuilder;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersDeleteResponse;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersOneRequestBuilder;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersOneResponse;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersUpdateRequestBuilder;
import com.apideck.unify.models.operations.async.AccountingSalesOrdersUpdateResponse;
import com.apideck.unify.operations.AccountingSalesOrdersAdd;
import com.apideck.unify.operations.AccountingSalesOrdersAll;
import com.apideck.unify.operations.AccountingSalesOrdersDelete;
import com.apideck.unify.operations.AccountingSalesOrdersOne;
import com.apideck.unify.operations.AccountingSalesOrdersUpdate;
import com.apideck.unify.utils.Headers;
import com.apideck.unify.utils.Options;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncSalesOrders {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final SalesOrders syncSDK;

    AsyncSalesOrders(SalesOrders syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public SalesOrders sync() {
        return syncSDK;
    }


    /**
     * List Sales Orders
     * 
     * <p>List Sales Orders
     * 
     * @return The async call builder
     */
    public AccountingSalesOrdersAllRequestBuilder list() {
        return new AccountingSalesOrdersAllRequestBuilder(sdkConfiguration);
    }

    /**
     * List Sales Orders
     * 
     * <p>List Sales Orders
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AccountingSalesOrdersAllResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersAllResponse> list(AccountingSalesOrdersAllRequest request) {
        return list(request, Optional.empty());
    }

    /**
     * List Sales Orders
     * 
     * <p>List Sales Orders
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<AccountingSalesOrdersAllResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersAllResponse> list(AccountingSalesOrdersAllRequest request, Optional<Options> options) {
        AsyncRequestOperation<AccountingSalesOrdersAllRequest, AccountingSalesOrdersAllResponse> operation
              = new AccountingSalesOrdersAll.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Create Sales Order
     * 
     * <p>Create Sales Order
     * 
     * @return The async call builder
     */
    public AccountingSalesOrdersAddRequestBuilder create() {
        return new AccountingSalesOrdersAddRequestBuilder(sdkConfiguration);
    }

    /**
     * Create Sales Order
     * 
     * <p>Create Sales Order
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AccountingSalesOrdersAddResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersAddResponse> create(AccountingSalesOrdersAddRequest request) {
        return create(request, Optional.empty());
    }

    /**
     * Create Sales Order
     * 
     * <p>Create Sales Order
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<AccountingSalesOrdersAddResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersAddResponse> create(AccountingSalesOrdersAddRequest request, Optional<Options> options) {
        AsyncRequestOperation<AccountingSalesOrdersAddRequest, AccountingSalesOrdersAddResponse> operation
              = new AccountingSalesOrdersAdd.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Sales Order
     * 
     * <p>Get Sales Order
     * 
     * @return The async call builder
     */
    public AccountingSalesOrdersOneRequestBuilder get() {
        return new AccountingSalesOrdersOneRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Sales Order
     * 
     * <p>Get Sales Order
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AccountingSalesOrdersOneResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersOneResponse> get(AccountingSalesOrdersOneRequest request) {
        return get(request, Optional.empty());
    }

    /**
     * Get Sales Order
     * 
     * <p>Get Sales Order
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<AccountingSalesOrdersOneResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersOneResponse> get(AccountingSalesOrdersOneRequest request, Optional<Options> options) {
        AsyncRequestOperation<AccountingSalesOrdersOneRequest, AccountingSalesOrdersOneResponse> operation
              = new AccountingSalesOrdersOne.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Update Sales Order
     * 
     * <p>Update Sales Order
     * 
     * @return The async call builder
     */
    public AccountingSalesOrdersUpdateRequestBuilder update() {
        return new AccountingSalesOrdersUpdateRequestBuilder(sdkConfiguration);
    }

    /**
     * Update Sales Order
     * 
     * <p>Update Sales Order
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AccountingSalesOrdersUpdateResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersUpdateResponse> update(AccountingSalesOrdersUpdateRequest request) {
        return update(request, Optional.empty());
    }

    /**
     * Update Sales Order
     * 
     * <p>Update Sales Order
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<AccountingSalesOrdersUpdateResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersUpdateResponse> update(AccountingSalesOrdersUpdateRequest request, Optional<Options> options) {
        AsyncRequestOperation<AccountingSalesOrdersUpdateRequest, AccountingSalesOrdersUpdateResponse> operation
              = new AccountingSalesOrdersUpdate.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete Sales Order
     * 
     * <p>Delete Sales Order
     * 
     * @return The async call builder
     */
    public AccountingSalesOrdersDeleteRequestBuilder delete() {
        return new AccountingSalesOrdersDeleteRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete Sales Order
     * 
     * <p>Delete Sales Order
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AccountingSalesOrdersDeleteResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersDeleteResponse> delete(AccountingSalesOrdersDeleteRequest request) {
        return delete(request, Optional.empty());
    }

    /**
     * Delete Sales Order
     * 
     * <p>Delete Sales Order
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<AccountingSalesOrdersDeleteResponse>} - The async response
     */
    public CompletableFuture<AccountingSalesOrdersDeleteResponse> delete(AccountingSalesOrdersDeleteRequest request, Optional<Options> options) {
        AsyncRequestOperation<AccountingSalesOrdersDeleteRequest, AccountingSalesOrdersDeleteResponse> operation
              = new AccountingSalesOrdersDelete.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
