/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify;

public class AsyncEcommerce {
    private final SDKConfiguration sdkConfiguration;
    private final AsyncOrders orders;
    private final AsyncProducts products;
    private final AsyncApideckCustomers customers;
    private final AsyncStores stores;
    private final Ecommerce syncSDK;

    AsyncEcommerce(Ecommerce syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.orders = new AsyncOrders(syncSDK.orders(), this.sdkConfiguration);
        this.products = new AsyncProducts(syncSDK.products(), this.sdkConfiguration);
        this.customers = new AsyncApideckCustomers(syncSDK.customers(), this.sdkConfiguration);
        this.stores = new AsyncStores(syncSDK.stores(), this.sdkConfiguration);
        this.syncSDK = syncSDK;
    }

    public final AsyncOrders orders() {
        return orders;
    }

    public final AsyncProducts products() {
        return products;
    }

    public final AsyncApideckCustomers customers() {
        return customers;
    }

    public final AsyncStores stores() {
        return stores;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Ecommerce sync() {
        return syncSDK;
    }

}
