/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.operations;

import static com.apideck.unify.operations.Operations.RequestOperation;

import com.apideck.unify.SDKConfiguration;
import com.apideck.unify.operations.CrmPipelinesUpdateOperation;
import com.apideck.unify.utils.Options;
import com.apideck.unify.utils.RetryConfig;
import com.apideck.unify.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;

public class CrmPipelinesUpdateRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private CrmPipelinesUpdateRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public CrmPipelinesUpdateRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public CrmPipelinesUpdateRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public CrmPipelinesUpdateRequestBuilder request(@Nonnull CrmPipelinesUpdateRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private CrmPipelinesUpdateRequest _buildRequest() {
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CrmPipelinesUpdateResponse call() throws Exception {
        Options options = optionsBuilder.build();
        RequestOperation<CrmPipelinesUpdateRequest, CrmPipelinesUpdateResponse> operation
              = new CrmPipelinesUpdateOperation(
                sdkConfiguration,
                options);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
