/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.operations;

import com.apideck.unify.models.components.ConnectionInput;
import com.apideck.unify.utils.SpeakeasyMetadata;
import com.apideck.unify.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class VaultConnectionSettingsUpdateRequest {
    /**
     * ID of the consumer which you want to get or push data from
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-apideck-consumer-id")
    private Optional<String> consumerId;

    /**
     * The ID of your Unify application
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-apideck-app-id")
    private Optional<String> appId;

    /**
     * Service ID of the resource to return
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=service_id")
    private String serviceId;

    /**
     * Unified API
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=unified_api")
    private String unifiedApi;

    /**
     * Name of the resource (plural)
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=resource")
    private String resource;

    /**
     * Fields that need to be updated on the resource
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private ConnectionInput connection;

    @JsonCreator
    public VaultConnectionSettingsUpdateRequest(
            Optional<String> consumerId,
            Optional<String> appId,
            String serviceId,
            String unifiedApi,
            String resource,
            ConnectionInput connection) {
        Utils.checkNotNull(consumerId, "consumerId");
        Utils.checkNotNull(appId, "appId");
        Utils.checkNotNull(serviceId, "serviceId");
        Utils.checkNotNull(unifiedApi, "unifiedApi");
        Utils.checkNotNull(resource, "resource");
        Utils.checkNotNull(connection, "connection");
        this.consumerId = consumerId;
        this.appId = appId;
        this.serviceId = serviceId;
        this.unifiedApi = unifiedApi;
        this.resource = resource;
        this.connection = connection;
    }
    
    public VaultConnectionSettingsUpdateRequest(
            String serviceId,
            String unifiedApi,
            String resource,
            ConnectionInput connection) {
        this(Optional.empty(), Optional.empty(), serviceId,
            unifiedApi, resource, connection);
    }

    /**
     * ID of the consumer which you want to get or push data from
     */
    @JsonIgnore
    public Optional<String> consumerId() {
        return consumerId;
    }

    /**
     * The ID of your Unify application
     */
    @JsonIgnore
    public Optional<String> appId() {
        return appId;
    }

    /**
     * Service ID of the resource to return
     */
    @JsonIgnore
    public String serviceId() {
        return serviceId;
    }

    /**
     * Unified API
     */
    @JsonIgnore
    public String unifiedApi() {
        return unifiedApi;
    }

    /**
     * Name of the resource (plural)
     */
    @JsonIgnore
    public String resource() {
        return resource;
    }

    /**
     * Fields that need to be updated on the resource
     */
    @JsonIgnore
    public ConnectionInput connection() {
        return connection;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of the consumer which you want to get or push data from
     */
    public VaultConnectionSettingsUpdateRequest withConsumerId(String consumerId) {
        Utils.checkNotNull(consumerId, "consumerId");
        this.consumerId = Optional.ofNullable(consumerId);
        return this;
    }


    /**
     * ID of the consumer which you want to get or push data from
     */
    public VaultConnectionSettingsUpdateRequest withConsumerId(Optional<String> consumerId) {
        Utils.checkNotNull(consumerId, "consumerId");
        this.consumerId = consumerId;
        return this;
    }

    /**
     * The ID of your Unify application
     */
    public VaultConnectionSettingsUpdateRequest withAppId(String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.ofNullable(appId);
        return this;
    }


    /**
     * The ID of your Unify application
     */
    public VaultConnectionSettingsUpdateRequest withAppId(Optional<String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }

    /**
     * Service ID of the resource to return
     */
    public VaultConnectionSettingsUpdateRequest withServiceId(String serviceId) {
        Utils.checkNotNull(serviceId, "serviceId");
        this.serviceId = serviceId;
        return this;
    }

    /**
     * Unified API
     */
    public VaultConnectionSettingsUpdateRequest withUnifiedApi(String unifiedApi) {
        Utils.checkNotNull(unifiedApi, "unifiedApi");
        this.unifiedApi = unifiedApi;
        return this;
    }

    /**
     * Name of the resource (plural)
     */
    public VaultConnectionSettingsUpdateRequest withResource(String resource) {
        Utils.checkNotNull(resource, "resource");
        this.resource = resource;
        return this;
    }

    /**
     * Fields that need to be updated on the resource
     */
    public VaultConnectionSettingsUpdateRequest withConnection(ConnectionInput connection) {
        Utils.checkNotNull(connection, "connection");
        this.connection = connection;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VaultConnectionSettingsUpdateRequest other = (VaultConnectionSettingsUpdateRequest) o;
        return 
            Utils.enhancedDeepEquals(this.consumerId, other.consumerId) &&
            Utils.enhancedDeepEquals(this.appId, other.appId) &&
            Utils.enhancedDeepEquals(this.serviceId, other.serviceId) &&
            Utils.enhancedDeepEquals(this.unifiedApi, other.unifiedApi) &&
            Utils.enhancedDeepEquals(this.resource, other.resource) &&
            Utils.enhancedDeepEquals(this.connection, other.connection);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            consumerId, appId, serviceId,
            unifiedApi, resource, connection);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VaultConnectionSettingsUpdateRequest.class,
                "consumerId", consumerId,
                "appId", appId,
                "serviceId", serviceId,
                "unifiedApi", unifiedApi,
                "resource", resource,
                "connection", connection);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> consumerId = Optional.empty();

        private Optional<String> appId = Optional.empty();

        private String serviceId;

        private String unifiedApi;

        private String resource;

        private ConnectionInput connection;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * ID of the consumer which you want to get or push data from
         */
        public Builder consumerId(String consumerId) {
            Utils.checkNotNull(consumerId, "consumerId");
            this.consumerId = Optional.ofNullable(consumerId);
            return this;
        }

        /**
         * ID of the consumer which you want to get or push data from
         */
        public Builder consumerId(Optional<String> consumerId) {
            Utils.checkNotNull(consumerId, "consumerId");
            this.consumerId = consumerId;
            return this;
        }


        /**
         * The ID of your Unify application
         */
        public Builder appId(String appId) {
            Utils.checkNotNull(appId, "appId");
            this.appId = Optional.ofNullable(appId);
            return this;
        }

        /**
         * The ID of your Unify application
         */
        public Builder appId(Optional<String> appId) {
            Utils.checkNotNull(appId, "appId");
            this.appId = appId;
            return this;
        }


        /**
         * Service ID of the resource to return
         */
        public Builder serviceId(String serviceId) {
            Utils.checkNotNull(serviceId, "serviceId");
            this.serviceId = serviceId;
            return this;
        }


        /**
         * Unified API
         */
        public Builder unifiedApi(String unifiedApi) {
            Utils.checkNotNull(unifiedApi, "unifiedApi");
            this.unifiedApi = unifiedApi;
            return this;
        }


        /**
         * Name of the resource (plural)
         */
        public Builder resource(String resource) {
            Utils.checkNotNull(resource, "resource");
            this.resource = resource;
            return this;
        }


        /**
         * Fields that need to be updated on the resource
         */
        public Builder connection(ConnectionInput connection) {
            Utils.checkNotNull(connection, "connection");
            this.connection = connection;
            return this;
        }

        public VaultConnectionSettingsUpdateRequest build() {

            return new VaultConnectionSettingsUpdateRequest(
                consumerId, appId, serviceId,
                unifiedApi, resource, connection);
        }

    }
}
