/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class AccountingEmployeesFilterStatus {

    public static final AccountingEmployeesFilterStatus ACTIVE = new AccountingEmployeesFilterStatus("active");
    public static final AccountingEmployeesFilterStatus INACTIVE = new AccountingEmployeesFilterStatus("inactive");
    public static final AccountingEmployeesFilterStatus TERMINATED = new AccountingEmployeesFilterStatus("terminated");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, AccountingEmployeesFilterStatus> values = createValuesMap();
    private static final Map<String, AccountingEmployeesFilterStatusEnum> enums = createEnumsMap();

    private final String value;

    private AccountingEmployeesFilterStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a AccountingEmployeesFilterStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as AccountingEmployeesFilterStatus
     */ 
    @JsonCreator
    public static AccountingEmployeesFilterStatus of(String value) {
        synchronized (AccountingEmployeesFilterStatus.class) {
            return values.computeIfAbsent(value, v -> new AccountingEmployeesFilterStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<AccountingEmployeesFilterStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AccountingEmployeesFilterStatus other = (AccountingEmployeesFilterStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "AccountingEmployeesFilterStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static AccountingEmployeesFilterStatus[] values() {
        synchronized (AccountingEmployeesFilterStatus.class) {
            return values.values().toArray(new AccountingEmployeesFilterStatus[] {});
        }
    }

    private static final Map<String, AccountingEmployeesFilterStatus> createValuesMap() {
        Map<String, AccountingEmployeesFilterStatus> map = new LinkedHashMap<>();
        map.put("active", ACTIVE);
        map.put("inactive", INACTIVE);
        map.put("terminated", TERMINATED);
        return map;
    }

    private static final Map<String, AccountingEmployeesFilterStatusEnum> createEnumsMap() {
        Map<String, AccountingEmployeesFilterStatusEnum> map = new HashMap<>();
        map.put("active", AccountingEmployeesFilterStatusEnum.ACTIVE);
        map.put("inactive", AccountingEmployeesFilterStatusEnum.INACTIVE);
        map.put("terminated", AccountingEmployeesFilterStatusEnum.TERMINATED);
        return map;
    }
    
    
    public enum AccountingEmployeesFilterStatusEnum {

        ACTIVE("active"),
        INACTIVE("inactive"),
        TERMINATED("terminated"),;

        private final String value;

        private AccountingEmployeesFilterStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

