/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.components;

import com.apideck.unify.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class CustomMappingInput {
    /**
     * Target Field Mapping value
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private String value;

    @JsonCreator
    public CustomMappingInput(
            @JsonProperty("value") @Nullable String value) {
        this.value = value;
    }
    
    public CustomMappingInput() {
        this(null);
    }

    /**
     * Target Field Mapping value
     */
    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Target Field Mapping value
     */
    public CustomMappingInput withValue(@Nullable String value) {
        this.value = value;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomMappingInput other = (CustomMappingInput) o;
        return 
            Utils.enhancedDeepEquals(this.value, other.value);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            value);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CustomMappingInput.class,
                "value", value);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String value;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Target Field Mapping value
         */
        public Builder value(@Nullable String value) {
            this.value = value;
            return this;
        }

        public CustomMappingInput build() {
            return new CustomMappingInput(
                value);
        }

    }
}
