/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * DepartmentStatus
 * 
 * <p>Based on the status some functionality is enabled or disabled.
 */
public class DepartmentStatus {

    public static final DepartmentStatus ACTIVE = new DepartmentStatus("active");
    public static final DepartmentStatus INACTIVE = new DepartmentStatus("inactive");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DepartmentStatus> values = createValuesMap();
    private static final Map<String, DepartmentStatusEnum> enums = createEnumsMap();

    private final String value;

    private DepartmentStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a DepartmentStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DepartmentStatus
     */ 
    @JsonCreator
    public static DepartmentStatus of(String value) {
        synchronized (DepartmentStatus.class) {
            return values.computeIfAbsent(value, v -> new DepartmentStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DepartmentStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DepartmentStatus other = (DepartmentStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DepartmentStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static DepartmentStatus[] values() {
        synchronized (DepartmentStatus.class) {
            return values.values().toArray(new DepartmentStatus[] {});
        }
    }

    private static final Map<String, DepartmentStatus> createValuesMap() {
        Map<String, DepartmentStatus> map = new LinkedHashMap<>();
        map.put("active", ACTIVE);
        map.put("inactive", INACTIVE);
        return map;
    }

    private static final Map<String, DepartmentStatusEnum> createEnumsMap() {
        Map<String, DepartmentStatusEnum> map = new HashMap<>();
        map.put("active", DepartmentStatusEnum.ACTIVE);
        map.put("inactive", DepartmentStatusEnum.INACTIVE);
        return map;
    }
    
    
    public enum DepartmentStatusEnum {

        ACTIVE("active"),
        INACTIVE("inactive"),;

        private final String value;

        private DepartmentStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

