/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.components;

import com.apideck.unify.utils.LazySingletonValue;
import com.apideck.unify.utils.SpeakeasyMetadata;
import com.apideck.unify.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class EmployeesSort {
    /**
     * The field on which to sort the Employees
     */
    @SpeakeasyMetadata("queryParam:name=by")
    private EmployeesSortBy by;

    /**
     * The direction in which to sort the results
     */
    @SpeakeasyMetadata("queryParam:name=direction")
    private SortDirection direction;

    @JsonCreator
    public EmployeesSort(
            @Nullable EmployeesSortBy by,
            @Nullable SortDirection direction) {
        this.by = by;
        this.direction = Optional.ofNullable(direction)
            .orElse(Builder._SINGLETON_VALUE_Direction.value());
    }
    
    public EmployeesSort() {
        this(null, null);
    }

    /**
     * The field on which to sort the Employees
     */
    public Optional<EmployeesSortBy> by() {
        return Optional.ofNullable(this.by);
    }

    /**
     * The direction in which to sort the results
     */
    public Optional<SortDirection> direction() {
        return Optional.ofNullable(this.direction);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The field on which to sort the Employees
     */
    public EmployeesSort withBy(@Nullable EmployeesSortBy by) {
        this.by = by;
        return this;
    }


    /**
     * The direction in which to sort the results
     */
    public EmployeesSort withDirection(@Nullable SortDirection direction) {
        this.direction = direction;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EmployeesSort other = (EmployeesSort) o;
        return 
            Utils.enhancedDeepEquals(this.by, other.by) &&
            Utils.enhancedDeepEquals(this.direction, other.direction);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            by, direction);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EmployeesSort.class,
                "by", by,
                "direction", direction);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private EmployeesSortBy by;

        private SortDirection direction;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The field on which to sort the Employees
         */
        public Builder by(@Nullable EmployeesSortBy by) {
            this.by = by;
            return this;
        }

        /**
         * The direction in which to sort the results
         */
        public Builder direction(@Nullable SortDirection direction) {
            this.direction = direction;
            return this;
        }

        public EmployeesSort build() {
            return new EmployeesSort(
                by, direction);
        }


        private static final LazySingletonValue<SortDirection> _SINGLETON_VALUE_Direction =
                new LazySingletonValue<>(
                        "direction",
                        "\"asc\"",
                        new TypeReference<SortDirection>() {});
    }
}
