/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.components;

import com.apideck.unify.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * GetBankFeedAccountsResponse
 * 
 * <p>Bank Feed Accounts
 */
public class GetBankFeedAccountsResponse {
    /**
     * HTTP Response Status Code
     */
    @JsonProperty("status_code")
    private long statusCode;

    /**
     * HTTP Response Status
     */
    @JsonProperty("status")
    private String status;

    /**
     * Apideck ID of service provider
     */
    @JsonProperty("service")
    private String service;

    /**
     * Unified API resource name
     */
    @JsonProperty("resource")
    private String resource;

    /**
     * Operation performed
     */
    @JsonProperty("operation")
    private String operation;


    @JsonProperty("data")
    private List<BankFeedAccount> data;

    /**
     * Response metadata
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    private Meta meta;

    /**
     * Links to navigate to previous or next pages through the API
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("links")
    private Links links;

    /**
     * Raw response from the integration when raw=true query param is provided
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("_raw")
    private JsonNullable<Map<String, Object>> raw;

    @JsonCreator
    public GetBankFeedAccountsResponse(
            @JsonProperty("status_code") long statusCode,
            @JsonProperty("status") @Nonnull String status,
            @JsonProperty("service") @Nonnull String service,
            @JsonProperty("resource") @Nonnull String resource,
            @JsonProperty("operation") @Nonnull String operation,
            @JsonProperty("data") @Nonnull List<BankFeedAccount> data,
            @JsonProperty("meta") @Nullable Meta meta,
            @JsonProperty("links") @Nullable Links links,
            @JsonProperty("_raw") @Nullable JsonNullable<Map<String, Object>> raw) {
        this.statusCode = statusCode;
        this.status = Optional.ofNullable(status)
            .orElseThrow(() -> new IllegalArgumentException("status cannot be null"));
        this.service = Optional.ofNullable(service)
            .orElseThrow(() -> new IllegalArgumentException("service cannot be null"));
        this.resource = Optional.ofNullable(resource)
            .orElseThrow(() -> new IllegalArgumentException("resource cannot be null"));
        this.operation = Optional.ofNullable(operation)
            .orElseThrow(() -> new IllegalArgumentException("operation cannot be null"));
        this.data = Optional.ofNullable(data)
            .orElseThrow(() -> new IllegalArgumentException("data cannot be null"));
        this.meta = meta;
        this.links = links;
        this.raw = Optional.ofNullable(raw)
            .orElse(JsonNullable.undefined());
    }
    
    public GetBankFeedAccountsResponse(
            long statusCode,
            @Nonnull String status,
            @Nonnull String service,
            @Nonnull String resource,
            @Nonnull String operation,
            @Nonnull List<BankFeedAccount> data) {
        this(statusCode, status, service,
            resource, operation, data,
            null, null, null);
    }

    /**
     * HTTP Response Status Code
     */
    public long statusCode() {
        return this.statusCode;
    }

    /**
     * HTTP Response Status
     */
    public String status() {
        return this.status;
    }

    /**
     * Apideck ID of service provider
     */
    public String service() {
        return this.service;
    }

    /**
     * Unified API resource name
     */
    public String resource() {
        return this.resource;
    }

    /**
     * Operation performed
     */
    public String operation() {
        return this.operation;
    }

    public List<BankFeedAccount> data() {
        return this.data;
    }

    /**
     * Response metadata
     */
    public Optional<Meta> meta() {
        return Optional.ofNullable(this.meta);
    }

    /**
     * Links to navigate to previous or next pages through the API
     */
    public Optional<Links> links() {
        return Optional.ofNullable(this.links);
    }

    /**
     * Raw response from the integration when raw=true query param is provided
     */
    public JsonNullable<Map<String, Object>> raw() {
        return this.raw;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP Response Status Code
     */
    public GetBankFeedAccountsResponse withStatusCode(long statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * HTTP Response Status
     */
    public GetBankFeedAccountsResponse withStatus(@Nonnull String status) {
        this.status = Utils.checkNotNull(status, "status");
        return this;
    }


    /**
     * Apideck ID of service provider
     */
    public GetBankFeedAccountsResponse withService(@Nonnull String service) {
        this.service = Utils.checkNotNull(service, "service");
        return this;
    }


    /**
     * Unified API resource name
     */
    public GetBankFeedAccountsResponse withResource(@Nonnull String resource) {
        this.resource = Utils.checkNotNull(resource, "resource");
        return this;
    }


    /**
     * Operation performed
     */
    public GetBankFeedAccountsResponse withOperation(@Nonnull String operation) {
        this.operation = Utils.checkNotNull(operation, "operation");
        return this;
    }


    public GetBankFeedAccountsResponse withData(@Nonnull List<BankFeedAccount> data) {
        this.data = Utils.checkNotNull(data, "data");
        return this;
    }


    /**
     * Response metadata
     */
    public GetBankFeedAccountsResponse withMeta(@Nullable Meta meta) {
        this.meta = meta;
        return this;
    }


    /**
     * Links to navigate to previous or next pages through the API
     */
    public GetBankFeedAccountsResponse withLinks(@Nullable Links links) {
        this.links = links;
        return this;
    }


    /**
     * Raw response from the integration when raw=true query param is provided
     */
    public GetBankFeedAccountsResponse withRaw(@Nullable Map<String, Object> raw) {
        this.raw = JsonNullable.of(raw);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetBankFeedAccountsResponse other = (GetBankFeedAccountsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.service, other.service) &&
            Utils.enhancedDeepEquals(this.resource, other.resource) &&
            Utils.enhancedDeepEquals(this.operation, other.operation) &&
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.meta, other.meta) &&
            Utils.enhancedDeepEquals(this.links, other.links) &&
            Utils.enhancedDeepEquals(this.raw, other.raw);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            statusCode, status, service,
            resource, operation, data,
            meta, links, raw);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetBankFeedAccountsResponse.class,
                "statusCode", statusCode,
                "status", status,
                "service", service,
                "resource", resource,
                "operation", operation,
                "data", data,
                "meta", meta,
                "links", links,
                "raw", raw);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long statusCode;

        private String status;

        private String service;

        private String resource;

        private String operation;

        private List<BankFeedAccount> data;

        private Meta meta;

        private Links links;

        private JsonNullable<Map<String, Object>> raw;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP Response Status Code
         */
        public Builder statusCode(long statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * HTTP Response Status
         */
        public Builder status(@Nonnull String status) {
            this.status = Utils.checkNotNull(status, "status");
            return this;
        }

        /**
         * Apideck ID of service provider
         */
        public Builder service(@Nonnull String service) {
            this.service = Utils.checkNotNull(service, "service");
            return this;
        }

        /**
         * Unified API resource name
         */
        public Builder resource(@Nonnull String resource) {
            this.resource = Utils.checkNotNull(resource, "resource");
            return this;
        }

        /**
         * Operation performed
         */
        public Builder operation(@Nonnull String operation) {
            this.operation = Utils.checkNotNull(operation, "operation");
            return this;
        }

        public Builder data(@Nonnull List<BankFeedAccount> data) {
            this.data = Utils.checkNotNull(data, "data");
            return this;
        }

        /**
         * Response metadata
         */
        public Builder meta(@Nullable Meta meta) {
            this.meta = meta;
            return this;
        }

        /**
         * Links to navigate to previous or next pages through the API
         */
        public Builder links(@Nullable Links links) {
            this.links = links;
            return this;
        }

        /**
         * Raw response from the integration when raw=true query param is provided
         */
        public Builder raw(@Nullable Map<String, Object> raw) {
            this.raw = JsonNullable.of(raw);
            return this;
        }

        public GetBankFeedAccountsResponse build() {
            return new GetBankFeedAccountsResponse(
                statusCode, status, service,
                resource, operation, data,
                meta, links, raw);
        }

    }
}
