/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.components;

import com.apideck.unify.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Boolean;
import java.lang.Deprecated;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * LedgerAccountCreateInput
 * 
 * <p>The writable shape of LedgerAccount for a batch create. Identical to [LedgerAccount](the model
 * returned on reads) with the read-only properties removed — the same properties the single-record
 * create endpoint rejects, so a batched record and a single-record create accept exactly the same
 * body.
 */
public class LedgerAccountCreateInput {
    /**
     * The human readable display ID used when displaying the account
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("display_id")
    private Optional<String> displayId;

    /**
     * The nominal code of the ledger account.
     * 
     * @deprecated field: This field is deprecated and may be removed in a future version..
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nominal_code")
    @Deprecated
    private JsonNullable<String> nominalCode;

    /**
     * The code assigned to the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private JsonNullable<String> code;

    /**
     * The classification of account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("classification")
    private JsonNullable<? extends LedgerAccountCreateInputClassification> classification;

    /**
     * The type of account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private Optional<? extends LedgerAccountCreateInputType> type;

    /**
     * The sub type of account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sub_type")
    private JsonNullable<String> subType;

    /**
     * The name of the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private JsonNullable<String> name;

    /**
     * The fully qualified name of the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fully_qualified_name")
    private JsonNullable<String> fullyQualifiedName;

    /**
     * The description of the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private JsonNullable<String> description;

    /**
     * The opening balance of the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("opening_balance")
    private JsonNullable<Double> openingBalance;

    /**
     * The current balance of the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("current_balance")
    private JsonNullable<Double> currentBalance;

    /**
     * Indicates the associated currency for an amount of money. Values correspond to [ISO
     * 4217](https://en.wikipedia.org/wiki/ISO_4217).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("currency")
    private JsonNullable<? extends Currency> currency;

    /**
     * The tax type of the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tax_type")
    private JsonNullable<String> taxType;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tax_rate")
    private Optional<? extends LinkedTaxRateInput> taxRate;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("level")
    private JsonNullable<Double> level;

    /**
     * Whether the account is active or not.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("active")
    private JsonNullable<Boolean> active;

    /**
     * The status of the account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private JsonNullable<? extends LedgerAccountCreateInputAccountStatus> status;

    /**
     * Whether the account is a header or not.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("header")
    private JsonNullable<Boolean> header;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bank_account")
    private Optional<? extends BankAccount> bankAccount;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parent_account")
    private Optional<? extends LedgerAccountCreateInputParentAccount> parentAccount;

    /**
     * Whether the account is a sub account or not.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sub_account")
    private JsonNullable<Boolean> subAccount;

    /**
     * Reconciliation Date means the last calendar day of each Reconciliation Period.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_reconciliation_date")
    private JsonNullable<LocalDate> lastReconciliationDate;

    /**
     * The subsidiaries the account belongs to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subsidiaries")
    private Optional<? extends List<LedgerAccountCreateInputSubsidiaries>> subsidiaries;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_fields")
    private Optional<? extends List<CustomField>> customFields;

    /**
     * A binary value used to detect updates to a object and prevent data conflicts. It is incremented each
     * time an update is made to the object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("row_version")
    private JsonNullable<String> rowVersion;

    /**
     * The pass_through property allows passing service-specific, custom data or structured modifications
     * in request body when creating or updating resources.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pass_through")
    private Optional<? extends List<PassThroughBody>> passThrough;

    @JsonCreator
    public LedgerAccountCreateInput(
            @JsonProperty("display_id") Optional<String> displayId,
            @JsonProperty("nominal_code") JsonNullable<String> nominalCode,
            @JsonProperty("code") JsonNullable<String> code,
            @JsonProperty("classification") JsonNullable<? extends LedgerAccountCreateInputClassification> classification,
            @JsonProperty("type") Optional<? extends LedgerAccountCreateInputType> type,
            @JsonProperty("sub_type") JsonNullable<String> subType,
            @JsonProperty("name") JsonNullable<String> name,
            @JsonProperty("fully_qualified_name") JsonNullable<String> fullyQualifiedName,
            @JsonProperty("description") JsonNullable<String> description,
            @JsonProperty("opening_balance") JsonNullable<Double> openingBalance,
            @JsonProperty("current_balance") JsonNullable<Double> currentBalance,
            @JsonProperty("currency") JsonNullable<? extends Currency> currency,
            @JsonProperty("tax_type") JsonNullable<String> taxType,
            @JsonProperty("tax_rate") Optional<? extends LinkedTaxRateInput> taxRate,
            @JsonProperty("level") JsonNullable<Double> level,
            @JsonProperty("active") JsonNullable<Boolean> active,
            @JsonProperty("status") JsonNullable<? extends LedgerAccountCreateInputAccountStatus> status,
            @JsonProperty("header") JsonNullable<Boolean> header,
            @JsonProperty("bank_account") Optional<? extends BankAccount> bankAccount,
            @JsonProperty("parent_account") Optional<? extends LedgerAccountCreateInputParentAccount> parentAccount,
            @JsonProperty("sub_account") JsonNullable<Boolean> subAccount,
            @JsonProperty("last_reconciliation_date") JsonNullable<LocalDate> lastReconciliationDate,
            @JsonProperty("subsidiaries") Optional<? extends List<LedgerAccountCreateInputSubsidiaries>> subsidiaries,
            @JsonProperty("custom_fields") Optional<? extends List<CustomField>> customFields,
            @JsonProperty("row_version") JsonNullable<String> rowVersion,
            @JsonProperty("pass_through") Optional<? extends List<PassThroughBody>> passThrough) {
        Utils.checkNotNull(displayId, "displayId");
        Utils.checkNotNull(nominalCode, "nominalCode");
        Utils.checkNotNull(code, "code");
        Utils.checkNotNull(classification, "classification");
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(subType, "subType");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(fullyQualifiedName, "fullyQualifiedName");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(openingBalance, "openingBalance");
        Utils.checkNotNull(currentBalance, "currentBalance");
        Utils.checkNotNull(currency, "currency");
        Utils.checkNotNull(taxType, "taxType");
        Utils.checkNotNull(taxRate, "taxRate");
        Utils.checkNotNull(level, "level");
        Utils.checkNotNull(active, "active");
        Utils.checkNotNull(status, "status");
        Utils.checkNotNull(header, "header");
        Utils.checkNotNull(bankAccount, "bankAccount");
        Utils.checkNotNull(parentAccount, "parentAccount");
        Utils.checkNotNull(subAccount, "subAccount");
        Utils.checkNotNull(lastReconciliationDate, "lastReconciliationDate");
        Utils.checkNotNull(subsidiaries, "subsidiaries");
        Utils.checkNotNull(customFields, "customFields");
        Utils.checkNotNull(rowVersion, "rowVersion");
        Utils.checkNotNull(passThrough, "passThrough");
        this.displayId = displayId;
        this.nominalCode = nominalCode;
        this.code = code;
        this.classification = classification;
        this.type = type;
        this.subType = subType;
        this.name = name;
        this.fullyQualifiedName = fullyQualifiedName;
        this.description = description;
        this.openingBalance = openingBalance;
        this.currentBalance = currentBalance;
        this.currency = currency;
        this.taxType = taxType;
        this.taxRate = taxRate;
        this.level = level;
        this.active = active;
        this.status = status;
        this.header = header;
        this.bankAccount = bankAccount;
        this.parentAccount = parentAccount;
        this.subAccount = subAccount;
        this.lastReconciliationDate = lastReconciliationDate;
        this.subsidiaries = subsidiaries;
        this.customFields = customFields;
        this.rowVersion = rowVersion;
        this.passThrough = passThrough;
    }
    
    public LedgerAccountCreateInput() {
        this(Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), Optional.empty(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), Optional.empty(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            Optional.empty(), Optional.empty(), JsonNullable.undefined(),
            JsonNullable.undefined(), Optional.empty(), Optional.empty(),
            JsonNullable.undefined(), Optional.empty());
    }

    /**
     * The human readable display ID used when displaying the account
     */
    @JsonIgnore
    public Optional<String> displayId() {
        return displayId;
    }

    /**
     * The nominal code of the ledger account.
     * 
     * @deprecated field: This field is deprecated and may be removed in a future version..
     */
    @Deprecated
    @JsonIgnore
    public JsonNullable<String> nominalCode() {
        return nominalCode;
    }

    /**
     * The code assigned to the account.
     */
    @JsonIgnore
    public JsonNullable<String> code() {
        return code;
    }

    /**
     * The classification of account.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<LedgerAccountCreateInputClassification> classification() {
        return (JsonNullable<LedgerAccountCreateInputClassification>) classification;
    }

    /**
     * The type of account.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<LedgerAccountCreateInputType> type() {
        return (Optional<LedgerAccountCreateInputType>) type;
    }

    /**
     * The sub type of account.
     */
    @JsonIgnore
    public JsonNullable<String> subType() {
        return subType;
    }

    /**
     * The name of the account.
     */
    @JsonIgnore
    public JsonNullable<String> name() {
        return name;
    }

    /**
     * The fully qualified name of the account.
     */
    @JsonIgnore
    public JsonNullable<String> fullyQualifiedName() {
        return fullyQualifiedName;
    }

    /**
     * The description of the account.
     */
    @JsonIgnore
    public JsonNullable<String> description() {
        return description;
    }

    /**
     * The opening balance of the account.
     */
    @JsonIgnore
    public JsonNullable<Double> openingBalance() {
        return openingBalance;
    }

    /**
     * The current balance of the account.
     */
    @JsonIgnore
    public JsonNullable<Double> currentBalance() {
        return currentBalance;
    }

    /**
     * Indicates the associated currency for an amount of money. Values correspond to [ISO
     * 4217](https://en.wikipedia.org/wiki/ISO_4217).
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<Currency> currency() {
        return (JsonNullable<Currency>) currency;
    }

    /**
     * The tax type of the account.
     */
    @JsonIgnore
    public JsonNullable<String> taxType() {
        return taxType;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<LinkedTaxRateInput> taxRate() {
        return (Optional<LinkedTaxRateInput>) taxRate;
    }

    @JsonIgnore
    public JsonNullable<Double> level() {
        return level;
    }

    /**
     * Whether the account is active or not.
     */
    @JsonIgnore
    public JsonNullable<Boolean> active() {
        return active;
    }

    /**
     * The status of the account.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<LedgerAccountCreateInputAccountStatus> status() {
        return (JsonNullable<LedgerAccountCreateInputAccountStatus>) status;
    }

    /**
     * Whether the account is a header or not.
     */
    @JsonIgnore
    public JsonNullable<Boolean> header() {
        return header;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<BankAccount> bankAccount() {
        return (Optional<BankAccount>) bankAccount;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<LedgerAccountCreateInputParentAccount> parentAccount() {
        return (Optional<LedgerAccountCreateInputParentAccount>) parentAccount;
    }

    /**
     * Whether the account is a sub account or not.
     */
    @JsonIgnore
    public JsonNullable<Boolean> subAccount() {
        return subAccount;
    }

    /**
     * Reconciliation Date means the last calendar day of each Reconciliation Period.
     */
    @JsonIgnore
    public JsonNullable<LocalDate> lastReconciliationDate() {
        return lastReconciliationDate;
    }

    /**
     * The subsidiaries the account belongs to.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<LedgerAccountCreateInputSubsidiaries>> subsidiaries() {
        return (Optional<List<LedgerAccountCreateInputSubsidiaries>>) subsidiaries;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<CustomField>> customFields() {
        return (Optional<List<CustomField>>) customFields;
    }

    /**
     * A binary value used to detect updates to a object and prevent data conflicts. It is incremented each
     * time an update is made to the object.
     */
    @JsonIgnore
    public JsonNullable<String> rowVersion() {
        return rowVersion;
    }

    /**
     * The pass_through property allows passing service-specific, custom data or structured modifications
     * in request body when creating or updating resources.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<PassThroughBody>> passThrough() {
        return (Optional<List<PassThroughBody>>) passThrough;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The human readable display ID used when displaying the account
     */
    public LedgerAccountCreateInput withDisplayId(String displayId) {
        Utils.checkNotNull(displayId, "displayId");
        this.displayId = Optional.ofNullable(displayId);
        return this;
    }


    /**
     * The human readable display ID used when displaying the account
     */
    public LedgerAccountCreateInput withDisplayId(Optional<String> displayId) {
        Utils.checkNotNull(displayId, "displayId");
        this.displayId = displayId;
        return this;
    }

    /**
     * The nominal code of the ledger account.
     * 
     * @deprecated field: This field is deprecated and may be removed in a future version..
     */
    @Deprecated
    public LedgerAccountCreateInput withNominalCode(String nominalCode) {
        Utils.checkNotNull(nominalCode, "nominalCode");
        this.nominalCode = JsonNullable.of(nominalCode);
        return this;
    }

    /**
     * The nominal code of the ledger account.
     * 
     * @deprecated field: This field is deprecated and may be removed in a future version..
     */
    @Deprecated
    public LedgerAccountCreateInput withNominalCode(JsonNullable<String> nominalCode) {
        Utils.checkNotNull(nominalCode, "nominalCode");
        this.nominalCode = nominalCode;
        return this;
    }

    /**
     * The code assigned to the account.
     */
    public LedgerAccountCreateInput withCode(String code) {
        Utils.checkNotNull(code, "code");
        this.code = JsonNullable.of(code);
        return this;
    }

    /**
     * The code assigned to the account.
     */
    public LedgerAccountCreateInput withCode(JsonNullable<String> code) {
        Utils.checkNotNull(code, "code");
        this.code = code;
        return this;
    }

    /**
     * The classification of account.
     */
    public LedgerAccountCreateInput withClassification(LedgerAccountCreateInputClassification classification) {
        Utils.checkNotNull(classification, "classification");
        this.classification = JsonNullable.of(classification);
        return this;
    }

    /**
     * The classification of account.
     */
    public LedgerAccountCreateInput withClassification(JsonNullable<? extends LedgerAccountCreateInputClassification> classification) {
        Utils.checkNotNull(classification, "classification");
        this.classification = classification;
        return this;
    }

    /**
     * The type of account.
     */
    public LedgerAccountCreateInput withType(LedgerAccountCreateInputType type) {
        Utils.checkNotNull(type, "type");
        this.type = Optional.ofNullable(type);
        return this;
    }


    /**
     * The type of account.
     */
    public LedgerAccountCreateInput withType(Optional<? extends LedgerAccountCreateInputType> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    /**
     * The sub type of account.
     */
    public LedgerAccountCreateInput withSubType(String subType) {
        Utils.checkNotNull(subType, "subType");
        this.subType = JsonNullable.of(subType);
        return this;
    }

    /**
     * The sub type of account.
     */
    public LedgerAccountCreateInput withSubType(JsonNullable<String> subType) {
        Utils.checkNotNull(subType, "subType");
        this.subType = subType;
        return this;
    }

    /**
     * The name of the account.
     */
    public LedgerAccountCreateInput withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = JsonNullable.of(name);
        return this;
    }

    /**
     * The name of the account.
     */
    public LedgerAccountCreateInput withName(JsonNullable<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * The fully qualified name of the account.
     */
    public LedgerAccountCreateInput withFullyQualifiedName(String fullyQualifiedName) {
        Utils.checkNotNull(fullyQualifiedName, "fullyQualifiedName");
        this.fullyQualifiedName = JsonNullable.of(fullyQualifiedName);
        return this;
    }

    /**
     * The fully qualified name of the account.
     */
    public LedgerAccountCreateInput withFullyQualifiedName(JsonNullable<String> fullyQualifiedName) {
        Utils.checkNotNull(fullyQualifiedName, "fullyQualifiedName");
        this.fullyQualifiedName = fullyQualifiedName;
        return this;
    }

    /**
     * The description of the account.
     */
    public LedgerAccountCreateInput withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = JsonNullable.of(description);
        return this;
    }

    /**
     * The description of the account.
     */
    public LedgerAccountCreateInput withDescription(JsonNullable<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * The opening balance of the account.
     */
    public LedgerAccountCreateInput withOpeningBalance(double openingBalance) {
        Utils.checkNotNull(openingBalance, "openingBalance");
        this.openingBalance = JsonNullable.of(openingBalance);
        return this;
    }

    /**
     * The opening balance of the account.
     */
    public LedgerAccountCreateInput withOpeningBalance(JsonNullable<Double> openingBalance) {
        Utils.checkNotNull(openingBalance, "openingBalance");
        this.openingBalance = openingBalance;
        return this;
    }

    /**
     * The current balance of the account.
     */
    public LedgerAccountCreateInput withCurrentBalance(double currentBalance) {
        Utils.checkNotNull(currentBalance, "currentBalance");
        this.currentBalance = JsonNullable.of(currentBalance);
        return this;
    }

    /**
     * The current balance of the account.
     */
    public LedgerAccountCreateInput withCurrentBalance(JsonNullable<Double> currentBalance) {
        Utils.checkNotNull(currentBalance, "currentBalance");
        this.currentBalance = currentBalance;
        return this;
    }

    /**
     * Indicates the associated currency for an amount of money. Values correspond to [ISO
     * 4217](https://en.wikipedia.org/wiki/ISO_4217).
     */
    public LedgerAccountCreateInput withCurrency(Currency currency) {
        Utils.checkNotNull(currency, "currency");
        this.currency = JsonNullable.of(currency);
        return this;
    }

    /**
     * Indicates the associated currency for an amount of money. Values correspond to [ISO
     * 4217](https://en.wikipedia.org/wiki/ISO_4217).
     */
    public LedgerAccountCreateInput withCurrency(JsonNullable<? extends Currency> currency) {
        Utils.checkNotNull(currency, "currency");
        this.currency = currency;
        return this;
    }

    /**
     * The tax type of the account.
     */
    public LedgerAccountCreateInput withTaxType(String taxType) {
        Utils.checkNotNull(taxType, "taxType");
        this.taxType = JsonNullable.of(taxType);
        return this;
    }

    /**
     * The tax type of the account.
     */
    public LedgerAccountCreateInput withTaxType(JsonNullable<String> taxType) {
        Utils.checkNotNull(taxType, "taxType");
        this.taxType = taxType;
        return this;
    }

    public LedgerAccountCreateInput withTaxRate(LinkedTaxRateInput taxRate) {
        Utils.checkNotNull(taxRate, "taxRate");
        this.taxRate = Optional.ofNullable(taxRate);
        return this;
    }


    public LedgerAccountCreateInput withTaxRate(Optional<? extends LinkedTaxRateInput> taxRate) {
        Utils.checkNotNull(taxRate, "taxRate");
        this.taxRate = taxRate;
        return this;
    }

    public LedgerAccountCreateInput withLevel(double level) {
        Utils.checkNotNull(level, "level");
        this.level = JsonNullable.of(level);
        return this;
    }

    public LedgerAccountCreateInput withLevel(JsonNullable<Double> level) {
        Utils.checkNotNull(level, "level");
        this.level = level;
        return this;
    }

    /**
     * Whether the account is active or not.
     */
    public LedgerAccountCreateInput withActive(boolean active) {
        Utils.checkNotNull(active, "active");
        this.active = JsonNullable.of(active);
        return this;
    }

    /**
     * Whether the account is active or not.
     */
    public LedgerAccountCreateInput withActive(JsonNullable<Boolean> active) {
        Utils.checkNotNull(active, "active");
        this.active = active;
        return this;
    }

    /**
     * The status of the account.
     */
    public LedgerAccountCreateInput withStatus(LedgerAccountCreateInputAccountStatus status) {
        Utils.checkNotNull(status, "status");
        this.status = JsonNullable.of(status);
        return this;
    }

    /**
     * The status of the account.
     */
    public LedgerAccountCreateInput withStatus(JsonNullable<? extends LedgerAccountCreateInputAccountStatus> status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    /**
     * Whether the account is a header or not.
     */
    public LedgerAccountCreateInput withHeader(boolean header) {
        Utils.checkNotNull(header, "header");
        this.header = JsonNullable.of(header);
        return this;
    }

    /**
     * Whether the account is a header or not.
     */
    public LedgerAccountCreateInput withHeader(JsonNullable<Boolean> header) {
        Utils.checkNotNull(header, "header");
        this.header = header;
        return this;
    }

    public LedgerAccountCreateInput withBankAccount(BankAccount bankAccount) {
        Utils.checkNotNull(bankAccount, "bankAccount");
        this.bankAccount = Optional.ofNullable(bankAccount);
        return this;
    }


    public LedgerAccountCreateInput withBankAccount(Optional<? extends BankAccount> bankAccount) {
        Utils.checkNotNull(bankAccount, "bankAccount");
        this.bankAccount = bankAccount;
        return this;
    }

    public LedgerAccountCreateInput withParentAccount(LedgerAccountCreateInputParentAccount parentAccount) {
        Utils.checkNotNull(parentAccount, "parentAccount");
        this.parentAccount = Optional.ofNullable(parentAccount);
        return this;
    }


    public LedgerAccountCreateInput withParentAccount(Optional<? extends LedgerAccountCreateInputParentAccount> parentAccount) {
        Utils.checkNotNull(parentAccount, "parentAccount");
        this.parentAccount = parentAccount;
        return this;
    }

    /**
     * Whether the account is a sub account or not.
     */
    public LedgerAccountCreateInput withSubAccount(boolean subAccount) {
        Utils.checkNotNull(subAccount, "subAccount");
        this.subAccount = JsonNullable.of(subAccount);
        return this;
    }

    /**
     * Whether the account is a sub account or not.
     */
    public LedgerAccountCreateInput withSubAccount(JsonNullable<Boolean> subAccount) {
        Utils.checkNotNull(subAccount, "subAccount");
        this.subAccount = subAccount;
        return this;
    }

    /**
     * Reconciliation Date means the last calendar day of each Reconciliation Period.
     */
    public LedgerAccountCreateInput withLastReconciliationDate(LocalDate lastReconciliationDate) {
        Utils.checkNotNull(lastReconciliationDate, "lastReconciliationDate");
        this.lastReconciliationDate = JsonNullable.of(lastReconciliationDate);
        return this;
    }

    /**
     * Reconciliation Date means the last calendar day of each Reconciliation Period.
     */
    public LedgerAccountCreateInput withLastReconciliationDate(JsonNullable<LocalDate> lastReconciliationDate) {
        Utils.checkNotNull(lastReconciliationDate, "lastReconciliationDate");
        this.lastReconciliationDate = lastReconciliationDate;
        return this;
    }

    /**
     * The subsidiaries the account belongs to.
     */
    public LedgerAccountCreateInput withSubsidiaries(List<LedgerAccountCreateInputSubsidiaries> subsidiaries) {
        Utils.checkNotNull(subsidiaries, "subsidiaries");
        this.subsidiaries = Optional.ofNullable(subsidiaries);
        return this;
    }


    /**
     * The subsidiaries the account belongs to.
     */
    public LedgerAccountCreateInput withSubsidiaries(Optional<? extends List<LedgerAccountCreateInputSubsidiaries>> subsidiaries) {
        Utils.checkNotNull(subsidiaries, "subsidiaries");
        this.subsidiaries = subsidiaries;
        return this;
    }

    public LedgerAccountCreateInput withCustomFields(List<CustomField> customFields) {
        Utils.checkNotNull(customFields, "customFields");
        this.customFields = Optional.ofNullable(customFields);
        return this;
    }


    public LedgerAccountCreateInput withCustomFields(Optional<? extends List<CustomField>> customFields) {
        Utils.checkNotNull(customFields, "customFields");
        this.customFields = customFields;
        return this;
    }

    /**
     * A binary value used to detect updates to a object and prevent data conflicts. It is incremented each
     * time an update is made to the object.
     */
    public LedgerAccountCreateInput withRowVersion(String rowVersion) {
        Utils.checkNotNull(rowVersion, "rowVersion");
        this.rowVersion = JsonNullable.of(rowVersion);
        return this;
    }

    /**
     * A binary value used to detect updates to a object and prevent data conflicts. It is incremented each
     * time an update is made to the object.
     */
    public LedgerAccountCreateInput withRowVersion(JsonNullable<String> rowVersion) {
        Utils.checkNotNull(rowVersion, "rowVersion");
        this.rowVersion = rowVersion;
        return this;
    }

    /**
     * The pass_through property allows passing service-specific, custom data or structured modifications
     * in request body when creating or updating resources.
     */
    public LedgerAccountCreateInput withPassThrough(List<PassThroughBody> passThrough) {
        Utils.checkNotNull(passThrough, "passThrough");
        this.passThrough = Optional.ofNullable(passThrough);
        return this;
    }


    /**
     * The pass_through property allows passing service-specific, custom data or structured modifications
     * in request body when creating or updating resources.
     */
    public LedgerAccountCreateInput withPassThrough(Optional<? extends List<PassThroughBody>> passThrough) {
        Utils.checkNotNull(passThrough, "passThrough");
        this.passThrough = passThrough;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LedgerAccountCreateInput other = (LedgerAccountCreateInput) o;
        return 
            Utils.enhancedDeepEquals(this.displayId, other.displayId) &&
            Utils.enhancedDeepEquals(this.nominalCode, other.nominalCode) &&
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.classification, other.classification) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.subType, other.subType) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.fullyQualifiedName, other.fullyQualifiedName) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.openingBalance, other.openingBalance) &&
            Utils.enhancedDeepEquals(this.currentBalance, other.currentBalance) &&
            Utils.enhancedDeepEquals(this.currency, other.currency) &&
            Utils.enhancedDeepEquals(this.taxType, other.taxType) &&
            Utils.enhancedDeepEquals(this.taxRate, other.taxRate) &&
            Utils.enhancedDeepEquals(this.level, other.level) &&
            Utils.enhancedDeepEquals(this.active, other.active) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.header, other.header) &&
            Utils.enhancedDeepEquals(this.bankAccount, other.bankAccount) &&
            Utils.enhancedDeepEquals(this.parentAccount, other.parentAccount) &&
            Utils.enhancedDeepEquals(this.subAccount, other.subAccount) &&
            Utils.enhancedDeepEquals(this.lastReconciliationDate, other.lastReconciliationDate) &&
            Utils.enhancedDeepEquals(this.subsidiaries, other.subsidiaries) &&
            Utils.enhancedDeepEquals(this.customFields, other.customFields) &&
            Utils.enhancedDeepEquals(this.rowVersion, other.rowVersion) &&
            Utils.enhancedDeepEquals(this.passThrough, other.passThrough);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            displayId, nominalCode, code,
            classification, type, subType,
            name, fullyQualifiedName, description,
            openingBalance, currentBalance, currency,
            taxType, taxRate, level,
            active, status, header,
            bankAccount, parentAccount, subAccount,
            lastReconciliationDate, subsidiaries, customFields,
            rowVersion, passThrough);
    }
    
    @Override
    public String toString() {
        return Utils.toString(LedgerAccountCreateInput.class,
                "displayId", displayId,
                "nominalCode", nominalCode,
                "code", code,
                "classification", classification,
                "type", type,
                "subType", subType,
                "name", name,
                "fullyQualifiedName", fullyQualifiedName,
                "description", description,
                "openingBalance", openingBalance,
                "currentBalance", currentBalance,
                "currency", currency,
                "taxType", taxType,
                "taxRate", taxRate,
                "level", level,
                "active", active,
                "status", status,
                "header", header,
                "bankAccount", bankAccount,
                "parentAccount", parentAccount,
                "subAccount", subAccount,
                "lastReconciliationDate", lastReconciliationDate,
                "subsidiaries", subsidiaries,
                "customFields", customFields,
                "rowVersion", rowVersion,
                "passThrough", passThrough);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> displayId = Optional.empty();

        @Deprecated
        private JsonNullable<String> nominalCode = JsonNullable.undefined();

        private JsonNullable<String> code = JsonNullable.undefined();

        private JsonNullable<? extends LedgerAccountCreateInputClassification> classification = JsonNullable.undefined();

        private Optional<? extends LedgerAccountCreateInputType> type = Optional.empty();

        private JsonNullable<String> subType = JsonNullable.undefined();

        private JsonNullable<String> name = JsonNullable.undefined();

        private JsonNullable<String> fullyQualifiedName = JsonNullable.undefined();

        private JsonNullable<String> description = JsonNullable.undefined();

        private JsonNullable<Double> openingBalance = JsonNullable.undefined();

        private JsonNullable<Double> currentBalance = JsonNullable.undefined();

        private JsonNullable<? extends Currency> currency = JsonNullable.undefined();

        private JsonNullable<String> taxType = JsonNullable.undefined();

        private Optional<? extends LinkedTaxRateInput> taxRate = Optional.empty();

        private JsonNullable<Double> level = JsonNullable.undefined();

        private JsonNullable<Boolean> active = JsonNullable.undefined();

        private JsonNullable<? extends LedgerAccountCreateInputAccountStatus> status = JsonNullable.undefined();

        private JsonNullable<Boolean> header = JsonNullable.undefined();

        private Optional<? extends BankAccount> bankAccount = Optional.empty();

        private Optional<? extends LedgerAccountCreateInputParentAccount> parentAccount = Optional.empty();

        private JsonNullable<Boolean> subAccount = JsonNullable.undefined();

        private JsonNullable<LocalDate> lastReconciliationDate = JsonNullable.undefined();

        private Optional<? extends List<LedgerAccountCreateInputSubsidiaries>> subsidiaries = Optional.empty();

        private Optional<? extends List<CustomField>> customFields = Optional.empty();

        private JsonNullable<String> rowVersion = JsonNullable.undefined();

        private Optional<? extends List<PassThroughBody>> passThrough = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The human readable display ID used when displaying the account
         */
        public Builder displayId(String displayId) {
            Utils.checkNotNull(displayId, "displayId");
            this.displayId = Optional.ofNullable(displayId);
            return this;
        }

        /**
         * The human readable display ID used when displaying the account
         */
        public Builder displayId(Optional<String> displayId) {
            Utils.checkNotNull(displayId, "displayId");
            this.displayId = displayId;
            return this;
        }


        /**
         * The nominal code of the ledger account.
         * 
         * @deprecated field: This field is deprecated and may be removed in a future version..
         */
        @Deprecated
        public Builder nominalCode(String nominalCode) {
            Utils.checkNotNull(nominalCode, "nominalCode");
            this.nominalCode = JsonNullable.of(nominalCode);
            return this;
        }

        /**
         * The nominal code of the ledger account.
         * 
         * @deprecated field: This field is deprecated and may be removed in a future version..
         */
        @Deprecated
        public Builder nominalCode(JsonNullable<String> nominalCode) {
            Utils.checkNotNull(nominalCode, "nominalCode");
            this.nominalCode = nominalCode;
            return this;
        }


        /**
         * The code assigned to the account.
         */
        public Builder code(String code) {
            Utils.checkNotNull(code, "code");
            this.code = JsonNullable.of(code);
            return this;
        }

        /**
         * The code assigned to the account.
         */
        public Builder code(JsonNullable<String> code) {
            Utils.checkNotNull(code, "code");
            this.code = code;
            return this;
        }


        /**
         * The classification of account.
         */
        public Builder classification(LedgerAccountCreateInputClassification classification) {
            Utils.checkNotNull(classification, "classification");
            this.classification = JsonNullable.of(classification);
            return this;
        }

        /**
         * The classification of account.
         */
        public Builder classification(JsonNullable<? extends LedgerAccountCreateInputClassification> classification) {
            Utils.checkNotNull(classification, "classification");
            this.classification = classification;
            return this;
        }


        /**
         * The type of account.
         */
        public Builder type(LedgerAccountCreateInputType type) {
            Utils.checkNotNull(type, "type");
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * The type of account.
         */
        public Builder type(Optional<? extends LedgerAccountCreateInputType> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }


        /**
         * The sub type of account.
         */
        public Builder subType(String subType) {
            Utils.checkNotNull(subType, "subType");
            this.subType = JsonNullable.of(subType);
            return this;
        }

        /**
         * The sub type of account.
         */
        public Builder subType(JsonNullable<String> subType) {
            Utils.checkNotNull(subType, "subType");
            this.subType = subType;
            return this;
        }


        /**
         * The name of the account.
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = JsonNullable.of(name);
            return this;
        }

        /**
         * The name of the account.
         */
        public Builder name(JsonNullable<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        /**
         * The fully qualified name of the account.
         */
        public Builder fullyQualifiedName(String fullyQualifiedName) {
            Utils.checkNotNull(fullyQualifiedName, "fullyQualifiedName");
            this.fullyQualifiedName = JsonNullable.of(fullyQualifiedName);
            return this;
        }

        /**
         * The fully qualified name of the account.
         */
        public Builder fullyQualifiedName(JsonNullable<String> fullyQualifiedName) {
            Utils.checkNotNull(fullyQualifiedName, "fullyQualifiedName");
            this.fullyQualifiedName = fullyQualifiedName;
            return this;
        }


        /**
         * The description of the account.
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = JsonNullable.of(description);
            return this;
        }

        /**
         * The description of the account.
         */
        public Builder description(JsonNullable<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }


        /**
         * The opening balance of the account.
         */
        public Builder openingBalance(double openingBalance) {
            Utils.checkNotNull(openingBalance, "openingBalance");
            this.openingBalance = JsonNullable.of(openingBalance);
            return this;
        }

        /**
         * The opening balance of the account.
         */
        public Builder openingBalance(JsonNullable<Double> openingBalance) {
            Utils.checkNotNull(openingBalance, "openingBalance");
            this.openingBalance = openingBalance;
            return this;
        }


        /**
         * The current balance of the account.
         */
        public Builder currentBalance(double currentBalance) {
            Utils.checkNotNull(currentBalance, "currentBalance");
            this.currentBalance = JsonNullable.of(currentBalance);
            return this;
        }

        /**
         * The current balance of the account.
         */
        public Builder currentBalance(JsonNullable<Double> currentBalance) {
            Utils.checkNotNull(currentBalance, "currentBalance");
            this.currentBalance = currentBalance;
            return this;
        }


        /**
         * Indicates the associated currency for an amount of money. Values correspond to [ISO
         * 4217](https://en.wikipedia.org/wiki/ISO_4217).
         */
        public Builder currency(Currency currency) {
            Utils.checkNotNull(currency, "currency");
            this.currency = JsonNullable.of(currency);
            return this;
        }

        /**
         * Indicates the associated currency for an amount of money. Values correspond to [ISO
         * 4217](https://en.wikipedia.org/wiki/ISO_4217).
         */
        public Builder currency(JsonNullable<? extends Currency> currency) {
            Utils.checkNotNull(currency, "currency");
            this.currency = currency;
            return this;
        }


        /**
         * The tax type of the account.
         */
        public Builder taxType(String taxType) {
            Utils.checkNotNull(taxType, "taxType");
            this.taxType = JsonNullable.of(taxType);
            return this;
        }

        /**
         * The tax type of the account.
         */
        public Builder taxType(JsonNullable<String> taxType) {
            Utils.checkNotNull(taxType, "taxType");
            this.taxType = taxType;
            return this;
        }


        public Builder taxRate(LinkedTaxRateInput taxRate) {
            Utils.checkNotNull(taxRate, "taxRate");
            this.taxRate = Optional.ofNullable(taxRate);
            return this;
        }

        public Builder taxRate(Optional<? extends LinkedTaxRateInput> taxRate) {
            Utils.checkNotNull(taxRate, "taxRate");
            this.taxRate = taxRate;
            return this;
        }


        public Builder level(double level) {
            Utils.checkNotNull(level, "level");
            this.level = JsonNullable.of(level);
            return this;
        }

        public Builder level(JsonNullable<Double> level) {
            Utils.checkNotNull(level, "level");
            this.level = level;
            return this;
        }


        /**
         * Whether the account is active or not.
         */
        public Builder active(boolean active) {
            Utils.checkNotNull(active, "active");
            this.active = JsonNullable.of(active);
            return this;
        }

        /**
         * Whether the account is active or not.
         */
        public Builder active(JsonNullable<Boolean> active) {
            Utils.checkNotNull(active, "active");
            this.active = active;
            return this;
        }


        /**
         * The status of the account.
         */
        public Builder status(LedgerAccountCreateInputAccountStatus status) {
            Utils.checkNotNull(status, "status");
            this.status = JsonNullable.of(status);
            return this;
        }

        /**
         * The status of the account.
         */
        public Builder status(JsonNullable<? extends LedgerAccountCreateInputAccountStatus> status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }


        /**
         * Whether the account is a header or not.
         */
        public Builder header(boolean header) {
            Utils.checkNotNull(header, "header");
            this.header = JsonNullable.of(header);
            return this;
        }

        /**
         * Whether the account is a header or not.
         */
        public Builder header(JsonNullable<Boolean> header) {
            Utils.checkNotNull(header, "header");
            this.header = header;
            return this;
        }


        public Builder bankAccount(BankAccount bankAccount) {
            Utils.checkNotNull(bankAccount, "bankAccount");
            this.bankAccount = Optional.ofNullable(bankAccount);
            return this;
        }

        public Builder bankAccount(Optional<? extends BankAccount> bankAccount) {
            Utils.checkNotNull(bankAccount, "bankAccount");
            this.bankAccount = bankAccount;
            return this;
        }


        public Builder parentAccount(LedgerAccountCreateInputParentAccount parentAccount) {
            Utils.checkNotNull(parentAccount, "parentAccount");
            this.parentAccount = Optional.ofNullable(parentAccount);
            return this;
        }

        public Builder parentAccount(Optional<? extends LedgerAccountCreateInputParentAccount> parentAccount) {
            Utils.checkNotNull(parentAccount, "parentAccount");
            this.parentAccount = parentAccount;
            return this;
        }


        /**
         * Whether the account is a sub account or not.
         */
        public Builder subAccount(boolean subAccount) {
            Utils.checkNotNull(subAccount, "subAccount");
            this.subAccount = JsonNullable.of(subAccount);
            return this;
        }

        /**
         * Whether the account is a sub account or not.
         */
        public Builder subAccount(JsonNullable<Boolean> subAccount) {
            Utils.checkNotNull(subAccount, "subAccount");
            this.subAccount = subAccount;
            return this;
        }


        /**
         * Reconciliation Date means the last calendar day of each Reconciliation Period.
         */
        public Builder lastReconciliationDate(LocalDate lastReconciliationDate) {
            Utils.checkNotNull(lastReconciliationDate, "lastReconciliationDate");
            this.lastReconciliationDate = JsonNullable.of(lastReconciliationDate);
            return this;
        }

        /**
         * Reconciliation Date means the last calendar day of each Reconciliation Period.
         */
        public Builder lastReconciliationDate(JsonNullable<LocalDate> lastReconciliationDate) {
            Utils.checkNotNull(lastReconciliationDate, "lastReconciliationDate");
            this.lastReconciliationDate = lastReconciliationDate;
            return this;
        }


        /**
         * The subsidiaries the account belongs to.
         */
        public Builder subsidiaries(List<LedgerAccountCreateInputSubsidiaries> subsidiaries) {
            Utils.checkNotNull(subsidiaries, "subsidiaries");
            this.subsidiaries = Optional.ofNullable(subsidiaries);
            return this;
        }

        /**
         * The subsidiaries the account belongs to.
         */
        public Builder subsidiaries(Optional<? extends List<LedgerAccountCreateInputSubsidiaries>> subsidiaries) {
            Utils.checkNotNull(subsidiaries, "subsidiaries");
            this.subsidiaries = subsidiaries;
            return this;
        }


        public Builder customFields(List<CustomField> customFields) {
            Utils.checkNotNull(customFields, "customFields");
            this.customFields = Optional.ofNullable(customFields);
            return this;
        }

        public Builder customFields(Optional<? extends List<CustomField>> customFields) {
            Utils.checkNotNull(customFields, "customFields");
            this.customFields = customFields;
            return this;
        }


        /**
         * A binary value used to detect updates to a object and prevent data conflicts. It is incremented each
         * time an update is made to the object.
         */
        public Builder rowVersion(String rowVersion) {
            Utils.checkNotNull(rowVersion, "rowVersion");
            this.rowVersion = JsonNullable.of(rowVersion);
            return this;
        }

        /**
         * A binary value used to detect updates to a object and prevent data conflicts. It is incremented each
         * time an update is made to the object.
         */
        public Builder rowVersion(JsonNullable<String> rowVersion) {
            Utils.checkNotNull(rowVersion, "rowVersion");
            this.rowVersion = rowVersion;
            return this;
        }


        /**
         * The pass_through property allows passing service-specific, custom data or structured modifications
         * in request body when creating or updating resources.
         */
        public Builder passThrough(List<PassThroughBody> passThrough) {
            Utils.checkNotNull(passThrough, "passThrough");
            this.passThrough = Optional.ofNullable(passThrough);
            return this;
        }

        /**
         * The pass_through property allows passing service-specific, custom data or structured modifications
         * in request body when creating or updating resources.
         */
        public Builder passThrough(Optional<? extends List<PassThroughBody>> passThrough) {
            Utils.checkNotNull(passThrough, "passThrough");
            this.passThrough = passThrough;
            return this;
        }

        public LedgerAccountCreateInput build() {

            return new LedgerAccountCreateInput(
                displayId, nominalCode, code,
                classification, type, subType,
                name, fullyQualifiedName, description,
                openingBalance, currentBalance, currency,
                taxType, taxRate, level,
                active, status, header,
                bankAccount, parentAccount, subAccount,
                lastReconciliationDate, subsidiaries, customFields,
                rowVersion, passThrough);
        }

    }
}
