/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apideck.unify.models.components;


import com.apideck.unify.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;


public class LinkedTaxRateInput {

    /**
     * The ID of the object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private JsonNullable<String> id;

    /**
     * Rate of the tax rate
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rate")
    private JsonNullable<Double> rate;

    @JsonCreator
    public LinkedTaxRateInput(
            @JsonProperty("id") JsonNullable<String> id,
            @JsonProperty("rate") JsonNullable<Double> rate) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(rate, "rate");
        this.id = id;
        this.rate = rate;
    }
    
    public LinkedTaxRateInput() {
        this(JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * The ID of the object.
     */
    @JsonIgnore
    public JsonNullable<String> id() {
        return id;
    }

    /**
     * Rate of the tax rate
     */
    @JsonIgnore
    public JsonNullable<Double> rate() {
        return rate;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The ID of the object.
     */
    public LinkedTaxRateInput withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = JsonNullable.of(id);
        return this;
    }

    /**
     * The ID of the object.
     */
    public LinkedTaxRateInput withId(JsonNullable<String> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * Rate of the tax rate
     */
    public LinkedTaxRateInput withRate(double rate) {
        Utils.checkNotNull(rate, "rate");
        this.rate = JsonNullable.of(rate);
        return this;
    }

    /**
     * Rate of the tax rate
     */
    public LinkedTaxRateInput withRate(JsonNullable<Double> rate) {
        Utils.checkNotNull(rate, "rate");
        this.rate = rate;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LinkedTaxRateInput other = (LinkedTaxRateInput) o;
        return 
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.rate, other.rate);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            id,
            rate);
    }
    
    @Override
    public String toString() {
        return Utils.toString(LinkedTaxRateInput.class,
                "id", id,
                "rate", rate);
    }
    
    public final static class Builder {
 
        private JsonNullable<String> id = JsonNullable.undefined();
 
        private JsonNullable<Double> rate = JsonNullable.undefined();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of the object.
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = JsonNullable.of(id);
            return this;
        }

        /**
         * The ID of the object.
         */
        public Builder id(JsonNullable<String> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * Rate of the tax rate
         */
        public Builder rate(double rate) {
            Utils.checkNotNull(rate, "rate");
            this.rate = JsonNullable.of(rate);
            return this;
        }

        /**
         * Rate of the tax rate
         */
        public Builder rate(JsonNullable<Double> rate) {
            Utils.checkNotNull(rate, "rate");
            this.rate = rate;
            return this;
        }
        
        public LinkedTaxRateInput build() {
            return new LinkedTaxRateInput(
                id,
                rate);
        }
    }
}

