/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ProjectPhase
 * 
 * <p>Current phase of the project lifecycle
 */
public enum ProjectPhase {
    INITIATION("initiation"),
    PLANNING("planning"),
    EXECUTION("execution"),
    MONITORING("monitoring"),
    CLOSURE("closure"),
    OTHER("other");

    @JsonValue
    private final String value;

    ProjectPhase(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ProjectPhase> fromValue(String value) {
        for (ProjectPhase o: ProjectPhase.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

