/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.apideck.unify.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum ShowAs {
    FREE("free"),
    BUSY("busy");

    @JsonValue
    private final String value;

    private ShowAs(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
