workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Apideck-OAS:
        inputs:
            - location: ../unify/speakeasy-spec.yml
            - location: https://ci-spec-unify.s3.eu-central-1.amazonaws.com/speakeasy-spec.yml
        registry:
            location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck-oas
targets:
    apideck:
        target: java
        source: Apideck-OAS
        publish:
            java:
                ossrhUsername: WQZzlTg7
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck-oas-code-samples
            blocking: false
