/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.apideck.unify.models.operations.async;

import static com.apideck.unify.operations.Operations.AsyncRequestOperation;

import com.apideck.unify.SDKConfiguration;
import com.apideck.unify.models.operations.ProxyGetProxyRequest;
import com.apideck.unify.operations.ProxyGetProxy;
import com.apideck.unify.utils.Headers;
import com.apideck.unify.utils.Options;
import com.apideck.unify.utils.RetryConfig;
import com.apideck.unify.utils.Utils;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class ProxyGetProxyRequestBuilder {

    private ProxyGetProxyRequest request;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ProxyGetProxyRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ProxyGetProxyRequestBuilder request(ProxyGetProxyRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public ProxyGetProxyRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public ProxyGetProxyRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public CompletableFuture<ProxyGetProxyResponse> call() {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        AsyncRequestOperation<ProxyGetProxyRequest, ProxyGetProxyResponse> operation
              = new ProxyGetProxy.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
